### ISSUE TITLE
commands.Group() for slash commands

### ISSUE THREAD

**Issue by ErrorNoInternet** [EQUENOS/disnake#48]
### Summary

commands.Group(), but for slash commands (sub-commands)

### What is the feature request for?

disnake.ext.commands

### The Problem

I am trying to use sub-commands (for slash commands) with commands.Bot, but the only `Group` I found in the documentation is `commands.Group()` which is for regular commands.

### The Ideal Solution

Adding something like `commands.SlashCommandGroup()` that will allow us to make sub-commands with `commands.SlashCommandGroup().slash_command()`

**Comment by m1raynee** [comment]
`InvocableSlashCommand` have `sub_command` and `sub_command_group` attributes.
https://disnake.readthedocs.io/en/latest/ext/commands/api.html#disnake.ext.commands.InvokableSlashCommand.sub_command
https://disnake.readthedocs.io/en/latest/ext/commands/api.html#disnake.ext.commands.InvokableSlashCommand.sub_command_group

**Comment by thesadru** [comment]
To add to this, disnake depends on discord to handle the parsing and invocation of slash commands. You can read about how the groups work here: https://discord.com/developers/docs/interactions/application-commands#subcommands-and-subcommand-groups

**Comment by EQUENOS** [comment]
This feature already exists, but it differs from the usual text command group. Here's how it works:
```py
@bot.slash_command()
async def parent(inter):
    pass

@parent.sub_command()
async def subcmd(inter):
    pass
```
This will be displayed as `/parent subcmd`

You can make double nesting, like so:
```py
@bot.slash_command()
async def parent(inter):
    pass

@parent.sub_command_group()
async def group(inter):
    pass

@group.sub_command()
async def subcmd(inter):
    pass
```
This will be displayed as `/parent group subcmd`

**Comment by m1raynee** [comment]
mod party

**Comment by ErrorNoInternet** [comment]
Got it, thanks for helping!
