### ISSUE TITLE
"GuildCommandInteraction" is not a known member of module

### ISSUE THREAD

**Issue by LEv145** [EQUENOS/disnake#55]
### Summary

Code from examples dont work

### Reproduction Steps

I inserted the code from the examples into the project

### Minimal Reproducible Code

```python
https://github.com/EQUENOS/disnake/blob/master/examples/slash_commands/param.py


# Commands may be limited only to guilds with a special interaction annotation
@bot.slash_command()
async def guild_command(
    inter: disnake.GuildCommandInteraction
) -> None:
    ...
```

### Expected Results

That the code will work

### Actual Results

The code doesn't work

### Intents

None

### System Information

$ pip show disnake
Name: disnake
Version: 2.1.2
Summary: A Python wrapper for the Discord API
Home-page: https://github.com/EQUENOS/disnake
Author: Rapptz, EQUENOS
Author-email: 
License: MIT
Location: /home/lev145/PycharmProjects/MusicBot/venv/lib/python3.9/site-packages
Requires: aiohttp
Required-by: discord-disnake

### Checklist

- [X] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I love cats

**Comment by jgayfer** [comment]
The `...` is a placeholder for the command body. These examples are mostly to provide an example on how to setup slash commands, but I understand where the confusion comes from.

@EQUENOS Do you see any value in making the examples command value such that they will run? Even if it's just a dummy response.

**Comment by jgayfer** [comment]
I take that back, `...` is still valid Python. This is likely an installation issue then, and not an issue with the library.

If you add `import disnake` to your example it should work.

**Comment by Victorsitou** [comment]
> Do you see any value in making the examples command value such that they will run? Even if it's just a dummy response.

It would be good if we change `...` to `# Your command here`.
