### ISSUE TITLE
on_message_interaction doesn't work properly

### ISSUE THREAD

**Issue by PetitPotiron** [EQUENOS/disnake#84]
### Summary

When clicking on a button, the bot will receive an unknown interaction while it has not restarted.

### Reproduction Steps

- Create an `on_message_interaction` event and write the code to respond this inter **inside the `on_message_interaction` event**.
- Create a command which sends a message with a button.
- Start the bot.
- Invoke the command.
- Click the button.
- The event will raise a `disnake.errors.NotFound` error.
- Restart the bot.
- Click on the button sent before (do not reinvoke the command).
- The event will return the proper interaction instead of `disnake.NotFound`.

### Minimal Reproducible Code

```python
import disnake
from disnake.ext import commands


class Cog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.slash_command(guild_ids=["ids"])
    async def test(self, inter):
        view = disnake.ui.View()
        view.add_item(disnake.ui.Button(style=disnake.ButtonStyle.blurple, emoji="❤"))
        await inter.response.send_message("Do you love me?", view=view)

    @commands.Cog.listener()
    async def on_message_interaction(self, inter):
        await inter.response.send_message(f'You interacted with a component', ephemeral=True)


def setup(bot):
    bot.add_cog(Cog(bot))
```

### Expected Results

The `inter.response.send_message` responds to the message interaction without restarting the bot.

### Actual Results

The `inter.response.send_message` doesn't respond to the message interaction without restarting the bot.

### Intents

None

### System Information

- Python v3.10.0-final
- disnake v2.1.5-beta
    - disnake pkg_resources: v2.1.5
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19042

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### Additional Context

[from that message](https://discord.com/channels/808030843078836254/883342278280745030/902233142902013974) [to that message](https://discord.com/channels/808030843078836254/883342278280745030/902240624818929794)
on disnake & dislash.py (https://discord.gg/gJDbCw8aQy)

**Comment by jgayfer** [comment]
I cannot reproduce on `2.1.5`. The code as provided works great.

**Comment by PetitPotiron** [comment]
Hi, I still get this issue, but an awesome person helped me on Discord and gave me a fix : 
[] Add a timeout of 0.01 on the view

![context](https://user-images.githubusercontent.com/70655051/139532274-975ec0c9-fe5b-491d-834a-5aa07bfa1180.png)
